// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDE9vB2WY2CeoTySb9myfbwcqhLOBeHXhw',
    appId: '1:680408433362:web:3c74c6c5f1bf2a6d46e30b',
    messagingSenderId: '680408433362',
    projectId: 'test1-34de7',
    authDomain: 'test1-34de7.firebaseapp.com',
    storageBucket: 'test1-34de7.appspot.com',
    measurementId: 'G-SYF10N99K7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCajrM_v7S-aziBG4821HAe6sSOf3sL1FA',
    appId: '1:680408433362:android:6c7f1ff51f4032ad46e30b',
    messagingSenderId: '680408433362',
    projectId: 'test1-34de7',
    storageBucket: 'test1-34de7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALZsIIHNMBP5dVXPI8bVkUScjZKvGVVyA',
    appId: '1:680408433362:ios:6d6f01b51e3acdc546e30b',
    messagingSenderId: '680408433362',
    projectId: 'test1-34de7',
    storageBucket: 'test1-34de7.appspot.com',
    iosBundleId: 'com.example.abc',
  );
}
